### ISSUE TITLE
This implementation yields false results

### ISSUE THREAD

**Issue by aeneasr** [encukou/bresenham#1]
Drawing a line from (0,0) to (10,1) should roughly yield these points with Bresenham:

![image](https://user-images.githubusercontent.com/3372410/31826130-82f53c34-b5b4-11e7-96d3-54b36f7ac3ce.png)

[Source](http://bert.stuy.edu/pbrooks/graphics/demos/BresenhamDemo.htm)

This algorithm however yields the following results:

```
from bresenham import bresenham
print(list(bresenham(0,0,10,1)))
```

```
[(0, 0), (1, 0), (2, 0), (3, 0), (4, 0), (5, 0), (6, 0), (7, 0), (8, 0), (9, 0), (10, 1)]
```

See also:

* https://www.cs.drexel.edu/~introcs/Fa11/notes/08.3_MoreGraphics/Bresenham.html?CurrentSlide=4
* http://wm.ite.pl/articles/bresenham-demo-line.html

**Comment by encukou** [comment]
Indeed it would probably be better to treat the coordinates as centers of pixels, rather than their edges.

**Comment by dornheimer** [comment]
this seems to be an issue with how the error value is incremented at each step. the initial error value is multiplied by 2, but the error adjustments in the loop are not.

i made a pull request that should fix this.

**Comment by encukou** [comment]
Thank you!
Fixed in https://github.com/encukou/bresenham/pull/2
