### ISSUE TITLE
Vectorized implementation

### ISSUE THREAD

**Issue by marcotama** [encukou/bresenham#4]
Hi, I put together a vectorized implementation. Are you interested in adding it? If so, how would you like me to proceed?
The implementation is not an iterator: instead, it returns numpy arrays for Xs and Ys.

**Comment by marcotama** [comment]
I should add that I did a couple of simple tests and my implementation is 40x faster.

**Comment by encukou** [comment]
That sounds great! However, I think the simple implementation has its place:
* numpy is a pretty big dependency,
* the code is probably more straightforward,
* the API should not be changed lightly.

Still, anyone searching for `bresenham` should probably see the vectorized implementation as well.
I an see two ways to proceed:
* add it as a separate module here,
* make it a separate project, in which case I'd be happy to link to it from the README.
Which sounds better for you?

> I should add that I did a couple of simple tests and my implementation is 40x faster.

That sounds about right. Numpy is magic :)

**Comment by marcotama** [comment]
Hi @encukou 

I'd rather keep both implementations in the same package, as separate modules - it feels more Pythonic, and less confusing to users. This is all if you are happy to add a Numpy dependency.

As for the readability, I think the vectorized implementation is pretty straight-forward, and conceptually maybe even easier to understand than the non-vectorized implementation. Basically, it computes the points on the line at integer intervals on X or Y and then rounds the numbers, with some logic to handle `|m| > 1` and swapping `p1` with `p2`.

I made a PR so you can have a look yourself: #5
